add tel-update
tel-setup only extracts bootstrap changes. tel-update clones changes repo, but does not replace user data

diff --git a/bin/tel-setup b/bin/tel-setup
--- a/bin/tel-setup
+++ b/bin/tel-setup
@@ -1,90 +1,143 @@
 #!/usr/bin/env bash
+#TEL setup file
+#should be executed only once after the setup 
+
+#set color and update vars
+UPDATE=false
+WHITE=${1:-"38;5;07"}
+GREEN=${1:-"38;5;02"}
+RED=${1:-"38;5;01"}
+
+#set helper functions
+#todo:move them to helpers file and use them
+catch(){
+if [ $?  -ne 0 ]
+then
+        logf "${1}"
+        error "${1}"
+	error "please try again"
+        exit 0
+else
+	logf "done"
+fi
+}
+
+
+logf(){
+        echo "[$(date '+%Y-%m-%d %H:%M:%S')]: ${1}" >> ~/.log.tel
+}
+log() {
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "${1}"
+}
 error() {
 	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${RED}" "${1}"
 }
-rm_tel_data(){
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" " ! Warning ! this action will remove all TEL data from your device"
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Are you sure you wish to continue? Y/N"
+
+log "Updating Termux packages..."
+logf "apt-get upgrade"
+apt-get update -y && apt-get upgrade -y && logf "finished updating Termux packages" #print to screen as hotfix
+if [ -f ~/.tel/.installed ]; then #set update var if finished installation was detected
+    logf ".installed exists"
+    error "You should not run tel-setup again. This will replace all TEL files. Are you sure?(y/N)"
 	read -r user_reponse
 	if [ "$user_reponse" != 'y' ] && [ "$user_reponse" != 'Y' ]; then
-		error "User cancelled setup..." ; sleep 1 ; exit 1
+		exit 0
 	fi
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Wiping data..."
-	rm -rf ~/.tel
-	rm -rf ~/.oh-my-zsh
-	rm -f ~/.zshrc
-	rm -f ~/.zlogin # these will be all be overwritten by a full install of setup after .installed flag is removed anyway
-	rm -f ~/.aliases
-	rm -f ~/.envvar
-	rm -f ~/../usr/etc/motd
-}
-rm_user_data(){
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Removing user data..."
-	rm -rf ~/.oh-my-zsh
-	rm -f ~/.zshrc
-	rm -f ~/.zlogin
-	rm -f ~/.aliases
-	rm -f ~/.envvar
-	rm -rf ~/.tel/configs
-	rm -rf ~/.tel/data
-	rm -rf ~/.config
-	rm -f ~/../usr/etc/motd
-}
-remove_tel_data='false'
-remove_user_data='false'
 
-if [ "$1" == '-h' ] || [ "$1" == '--help' ] ; then
-	echo 'usage: tel-setup [OPTION]
-	--help 		display this help info
-	--update	get latest release updates
-	--reset 	setup release version (destructive)
-	--dev 		setup developer version (destructive)
-	--custom	setup custom version (destructive)
-	--extras	extra scripts'
-	exit 0
-elif [ "$1" == '--update' ] ; then
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting updates"
-	branch='master'
-elif [ "$1" == '--dev' ] ; then
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting developer version"
-	remove_tel_data='true'
-	branch='dev'
-elif [ "$1" == '--custom' ] ; then
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Which branch do you want to setup? e.g: staging"
-	read -r branch
-	remove_tel_data='true'
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting $branch"
-elif [ "$1" == '--reset' ] ; then
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Resetting & getting latest version"
-	remove_tel_data='true'
-	branch='master'
-elif [ "$1" == '--extras' ] ; then
-	if [ ! -f "$HOME/.tel/.installed" ]; then
-		error 'Extras can only be installed after TEL has been setup'
-	fi
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "launching extras installer..."
-	~/.tel/extras/setup.sh
-	exit 0
-elif [ -n "$1" ] ; then #user picked non option
-	error "Unrecognised input option..."
-	error "try 'tel-setup --help' to see availible options"
-	exit 1
+log "Installing required packages.."
+log "This may take a while..."
+logf "pkg install"
+catch "$(pkg install fzf sl cowsay openssh tree bc fd curl wget nano tmux zsh neofetch git make figlet ncurses-utils termux-api sed util-linux -y 2>&1)"
+
+log "Installing python"
+logf "python"
+catch "$(pkg install python -y 2>&1)" 
+
+log "Installing python package manager"
+logf "pip"
+catch "$(curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 2>&1)"
+catch "$(python get-pip.py 2>&1)"
+rm -f get-pip.py
+
+log "Installing python packages"
+logf "pip install"
+catch "$(pip install --user blessed lolcat powerline-status 2>&1)" #removed psutil
+logf "Finished packages download and installation"
+
+#other termux tools are listed in these files, idk if its necessary to maintain them
+#echo "/data/data/com.termux/files/usr/bin/tel-appcache" >> ~/../usr/var/lib/dpkg/info/termux-tools.list
+#echo "92a2c39cbbde0f366887d99a76358852  data/data/com.termux/files/usr/bin/tel-appcache" >> ~/../usr/var/lib/dpkg/info/termux-tools.md5sums
+
+#create required directories
+#todo: optimize this
+mkdir -p ~/.termux
+mkdir -p ~/.tel
+mkdir -p ~/.config
+mkdir -p ~/bin
+
+# # # # ZSH setup # # #
+log "Installing ohmyzsh"
+logf "ohmyzsh"
+sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended  > /dev/null 2>&1 && logf "finished installing OhMyZsh"
+chsh -s zsh #set zsh default shell
+
+#install zsh plugins
+#disabled because interferences with suggestion bar
+catch "$(git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions 2>&1)"
+catch "$(git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting 2>&1)"
+sed -i 's/robbyrussell/avit/g' ~/.zshrc
+sed -i 's/plugins=(git)/plugins=(git catimg fancy-ctrl-z zsh-syntax-highlighting)/g' ~/.zshrc #fzf maybe needed here
+
+# setup zsh history (share between windows)
+echo -e "\n# ZSH HISTORY #\nHISTSIZE=40000\nSAVEHIST=20000\nHISTFILE=~/.zsh_history\nsetopt INC_APPEND_HISTORY\nsetopt SHARE_HISTORY\n" >> ~/.zshrc
+# setup tel loading
+echo -e "	\n#|||||||||||||||#\n. ~/.tel/.telrc\n#|||||||||||||||#\n	" >> ~/.zshrc
+
+log "Installing TEL..." #todo: optimize this
+logf "tel data"
+
+#cp -rf ~/../usr/tel/termux-file-editor ~/bin
+#cp -rf ~/../usr/tel/termux-url-opener ~/bin
+
+# put thingies in actual location
+cp -rf ~/../usr/tel/. ~/
+#rm -rf ~/setup.sh	
+#cp -rTf ~/../usr/tel/.tel ~/.tel
+#cp -rTf ~/../usr/tel/.termux ~/.termux
+#cp -rf ~/../usr/tel/.config ~/
+#cp -rf ~/../usr/tel/.nano ~/
+#cp -rf ~/../usr/tel/.aliases ~/
+#cp -rf ~/../usr/tel/.envvar ~/
+#cp -rf ~/../usr/tel/.tmux.conf ~/
+#cp -rf ~/../usr/tel/.zlogin ~/
+#cp -rf ~/../usr/tel/.nanorc ~/
+
+
+log "Updating permissions..."
+logf "permissions"
+chmod +x ~/.tel/extras/*
+chmod +x ~/.tel/status/*
+chmod +x ~/.tel/scripts/*
+chmod +x ~/.tel/scripts/status_manager/*
+chmod +x ~/.tel/tutorials/*
+chmod +x ~/.tel/bin/*
+chmod +x ~/bin/* # scripts that receive files and urls shared to TEL
+chmod +x ~/../usr/bin/*
+
+if [ -f "$HOME/../usr/etc/motd_finished" ]; then
+	mv ~/../usr/etc/motd_finished ~/../usr/etc/motd #set final motd
+fi
+
+if [ "$UPDATE" = false ]; then
+	touch ~/.tel/.installed #mark setup finished
+        log "Installation Complete"
 else
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting updates"
-	branch='master'
+        log "Update Complete"
 fi
-
-if [ ! -f "$HOME/.tel/.installed" ]; then
-	pkg install wget unzip coreutils -y 2>&1 || (error 'failed to download required setup utils' && exit 1)
-fi
-
-cd ~/../usr/ || (error 'fatal error path does not exist: ~/../usr/' && exit 1)
-wget https://github.com/t-e-l/tel/raw/$branch/bootstrap/changes.zip 2>&1 || (error "failed to download update from $branch" && exit 1)
-[[ "$remove_tel_data" == "true" ]] && rm_tel_data
-[[ "$remove_user_data" == "true" ]] && rm_user_data
-unzip -o changes.zip 2>&1
-rm -f changes.zip
-chmod +x ~/../usr/bin/tel-setup
-chmod +x ~/../usr/bin/tel-applist
-chmod +x ~/../usr/tel/setup.sh
-./tel/setup.sh || error 'experienced error whilst running setup'
+logf "complete"
+log "app will restart in 3 seconds!"
+sleep 3
+tel-restart
+error 'Restart cannot be performed automatically when app is not active'
+error 'Please run the command "tel-restart" manually'
+exit 0
