simplify dir struct and setup

diff --git a/changes/usr/bin/tel-update b/changes/usr/bin/tel-update
--- a/changes/usr/bin/tel-update
+++ b/changes/usr/bin/tel-update
@@ -9,7 +9,7 @@ rm_tel_data(){
 	if [ "$user_reponse" != 'y' ] && [ "$user_reponse" != 'Y' ]; then
 		error "User cancelled setup..." ; sleep 1 ; exit 1
 	fi
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Wiping data..."
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Wiping data..."
 	rm -rf ~/.tel
 	rm -rf ~/.oh-my-zsh
 	rm -f ~/.zshrc
@@ -78,16 +78,17 @@ if [ ! -f "$HOME/.tel/.installed" ]; then
 	pkg install wget unzip coreutils git -y 2>&1 || (error 'failed to download required setup utils' && exit 1)
 fi
 
-cd ~/../usr/ || (error 'fatal error path does not exist: ~/../usr/' && exit 1)
+cd ~/.. || (error 'fatal error path does not exist: ~/../usr/' && exit 1)
 
-git clone https://github.com/t-e-l/bootstrap-changes
-#wget https://github.com/t-e-l/tel/raw/$branch/bootstrap/changes.zip 2>&1 || (error "failed to download update from $branch" && exit 1)
 [[ "$remove_tel_data" == "true" ]] && rm_tel_data
 [[ "$remove_user_data" == "true" ]] && rm_user_data
-#unzip -o changes.zip 2>&1
-mv bootstrap-changes/bin/* ~/../usr/bin/
 
-rm -rf bootstrap-changes
-chmod +x ~/../usr/bin/tel-setup
-chmod +x ~/../usr/bin/tel-applist
+#git clone https://github.com/t-e-l/bootstrap-changes
+wget https://github.com/t-e-l/bootstrap-changes/raw/$branch/changes.zip 2>&1 || (error "failed to download update from $branch" && exit 1)
+unzip -o changes.zip 2>&1
+rm -rf changes.zip
+#mv bootstrap-changes/bin/* ~/../usr/bin/ 
+#rm -rf bootstrap-changes
+
+chmod +x ~/../usr/bin/*
 #./tel/setup.sh || error 'experienced error whilst running setup'
